"""Build fast, standalone HCCF pages and the existing SPA entry-point bridge."""
from pathlib import Path
from html import escape
import argparse, hashlib, json, re, shutil

HERE=Path(__file__).resolve().parent
parser=argparse.ArgumentParser()
parser.add_argument('--site-root',type=Path,default=HERE.parent.parent if HERE.parent.name=='.hccf' else Path('/Users/abhishekpaluri/Downloads/HUManity website'))
parser.add_argument('--output',type=Path,default=HERE/'deploy')
args=parser.parse_args()
OUT=args.output; SITE=args.site_root
homes=json.loads((HERE/'homes.json').read_text())
assert 1 <= len(homes) <= 30 and len({x['id'] for x in homes})==len(homes)
assert all(re.fullmatch('[a-z0-9-]{1,80}',x['id']) and isinstance(x['goal'],int) and x['goal']>0 for x in homes)
ORIGIN='https://humanityorg.foundation'
BASE='/wheelsofhope/fund/'
LOGO='/manus-storage/Logos-2_1766126722043_d1980132.png'
h=lambda x:escape(str(x),quote=True)
def rupees(value):
    s=str(int(value)); tail=s[-3:]; head=s[:-3]; chunks=[]
    while head: chunks.insert(0,head[-2:]);head=head[:-2]
    return '₹'+(','.join(chunks)+',' if chunks else '')+tail
def icon(kind):
    paths={
      'heart':'<path d="M20 5c-3-3-7 0-8 2-1-2-5-5-8-2s-1 7 8 14c9-7 11-11 8-14Z"/>',
      'pin':'<path d="M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 1 1 14 0Z"/><circle cx="12" cy="9" r="2"/>',
      'people':'<circle cx="9" cy="7" r="3"/><path d="M3 20v-3a6 6 0 0 1 12 0v3M17 5a3 3 0 0 1 0 6m2 9v-3a5 5 0 0 0-2-4"/>',
      'check':'<path d="m5 12 4 4L19 6"/>',
      'lock':'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4M12 14v3"/>',
      'search':'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',
      'home':'<path d="m3 10 9-7 9 7M5 9v12h14V9M9 21v-7h6v7"/>',
      'shield':'<path d="M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6L12 2Z"/><path d="m8 12 3 3 5-6"/>',
    }
    return f'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">{paths[kind]}</svg>'
def image_path(home,index=0,width=1200):return f"/assets/hccf-homes/{home['id']}/{index+1}-{width}.webp"
def photo(home,index=0,width=1200,eager=False,css=''):
    return f'<img class="{css}" src="{image_path(home,index,width)}" srcset="{image_path(home,index,640)} 640w, {image_path(home,index,1200)} 1200w" sizes="{h("(max-width: 800px) 100vw, 55vw" if width==1200 else "(max-width: 560px) 100vw, (max-width: 800px) 50vw, 33vw")}" alt="{h(home["photos"][index][1])}" width="1200" height="900" {"fetchpriority=high" if eager else "loading=lazy"} decoding="async">'
def brand(link=True):
    content=f'<img src="{LOGO}" alt="HUManity Foundation" width="116" height="55"><span class="brand-label"><strong>HUManity</strong><span>ChildCare Institution Fund</span></span>'
    return f'<a class="brand" href="/">{content}</a>' if link else f'<div class="brand">{content}</div>'
def header(landing=False):
    nav=f'<span class="header-security">{icon("lock")} Secure giving</span><a class="btn" href="#donate">Donate now <span aria-hidden="true">↗</span></a>' if landing else '<a href="#homes">Meet the homes</a><a href="#how-it-works">How it works</a><a href="/wheelsofhope">Wheels of Hope</a><a class="btn" href="#homes">Support a home <span aria-hidden="true">↗</span></a>'
    return f'<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="wrap header-inner">{brand(not landing)}<nav class="header-nav" aria-label="{h("Donation" if landing else "Campaign")}">{nav}</nav></div></header>'
def footer(landing=False):
    return '<footer class="site-footer"><div class="wrap"><div class="footer-row"><div class="footer-brand"><span class="footer-wordmark"><b>HUM</b>anity</span><span>HUMANITY UPLIFTING MANKIND</span></div><div class="footer-links"><a href="mailto:contact@humanityorg.foundation">Donation support</a><a href="tel:+919912962885">+91 99129 62885</a><a href="/privacy" target="_blank" rel="noopener">Privacy policy ↗</a></div></div><div class="footer-bottom"><span>© 2026 HUManity Foundation. All rights reserved.</span><span>HUManity ChildCare Institution Fund · Telangana, India</span></div></div></footer>'
def progress(home):
    return f'''<div class="progress-block" data-progress="{h(home['id'])}" data-goal="{home['goal']}">
      <div class="progress-top"><span><strong data-raised>Checking…</strong><span class="visually-hidden"> funded and committed</span></span><span>of {rupees(home['goal'])}</span></div>
      <div class="progress-track" role="progressbar" aria-label="{h(home['name'])} yearly fundraising progress" aria-valuemin="0" aria-valuemax="{home['goal']}" aria-valuetext="Checking confirmed total"><span></span></div>
      <p class="progress-note" data-received>Confirmed receipts + yearly commitments</p></div>'''
def card(home):
    return f'''<article class="home-card" data-home="{h(home['id'])}" data-category="{home['category']}" data-search="{h((home['name']+' '+home['district']+' '+home['tag']).lower())}">
    <a class="card-link" data-home-link href="{BASE}{home['id']}/" aria-label="Read the story and support {h(home['name'])}">
    <div class="card-photo">{photo(home,width=640)}<span class="card-tag">{h(home['tag'])}</span></div>
    <div class="card-body"><p class="card-location">{icon('pin')}{h(home['district'])} · Telangana</p><h3>{h(home['name'])}</h3><p class="card-summary">{h(home['summary'])}</p><p class="card-residents">{icon('people')}{h(home['residents'])}</p>{progress(home)}<div class="card-cta">Read their story & support<span class="round-arrow" aria-hidden="true">↗</span></div></div></a></article>'''
def faq(items):
    return '<div class="faq-list">'+''.join(f'<details {"id=tax-details" if q.startswith("Why do you ask") else ""}><summary>{h(q)}</summary><p>{h(a)}</p></details>' for q,a in items)+'</div>'
def brand_motif():
    return '<svg class="brand-motif" viewBox="0 0 520 520" aria-hidden="true"><circle cx="260" cy="260" r="239"/><circle cx="260" cy="260" r="202"/><path d="M108 241 260 111l152 130M143 222v173h234V222M235 395v-80h50v80"/><path class="motif-heart" d="M260 270c-55-33-63-62-42-75 17-11 33-1 42 11 9-12 25-22 42-11 21 13 13 42-42 75Z"/></svg>'
def care_banner():
    return f'<section class="care-banner wrap" aria-label="The care every childhood deserves"><div class="care-banner-title"><span class="eyebrow">HUMANITY UPLIFTING MANKIND</span><h2>Big dreams begin<br>with everyday care.</h2></div><div class="care-value">{icon("home")}<span>A safe place<br><strong>to call home.</strong></span></div><div class="care-value">{icon("heart")}<span>A caring hand<br><strong>to count on.</strong></span></div><div class="care-value">{icon("people")}<span>A fair chance<br><strong>to dream bigger.</strong></span></div></section>'
common_faq=[
 ('How does monthly giving count toward the goal?','A confirmed ₹500 monthly donation represents a ₹6,000 commitment over 12 months. ₹1,000 monthly represents ₹12,000. We show this annual commitment toward the goal, alongside the amount actually received. Future instalments are not money already collected.'),
 ('What happens if I need to stop monthly giving?','Contact HUManity at contact@humanityorg.foundation or +91 99129 62885 for help with your subscription. When cancellation or an inactive subscription is confirmed, future instalments are removed from the committed total.'),
 ('Why do you ask for my name and ID details?','We need your name as per government ID, contact details and ID information to maintain donation records and provide your donation receipt and 80G documentation. Eligible donations to HUManity qualify for a 50% deduction under Section 80G, subject to applicable tax rules and limits. Your details are kept private and are not displayed on the fundraiser.'),
 ('What does the 50% 80G benefit mean?','Eligible donors can deduct 50% of the qualifying donation from taxable income, subject to the applicable qualifying limit. This is a deduction from taxable income, not a refund of half your donation. Section 80G is not available to individuals choosing the new tax regime. HUManity provides the relevant donation documentation.'),
 ('Who can I contact about a payment?','Contact contact@humanityorg.foundation or +91 99129 62885 with your Razorpay payment reference. If your bank shows a debit but confirmation is pending, use Check payment confirmation rather than making another payment.'),
]
def hub():
    return f'''{header()}<main id="main"><section class="hub-hero">{brand_motif()}<div class="wrap hero-layout"><div class="hero-copy"><span class="eyebrow campaign-kicker">A HUManity promise. A childhood protected.</span><h1>Help a home.<br>Hold a childhood<br><em>together.</em></h1><p>Behind every home is a childhood worth protecting. Help under-supported childcare institutions in Telangana meet the needs that keep everyday care going.</p><div class="hero-actions"><a class="btn" href="#homes">Find a home to support <span aria-hidden="true">↗</span></a><a class="text-link" href="#how-it-works">How your giving helps</a></div><div class="hero-proof"><span class="check-circle">{icon('check')}</span>Field-assessed needs. A dedicated goal for every home.</div></div><figure class="hero-image"><img src="/assets/hccf-brand/care-1200.webp" srcset="/assets/hccf-brand/care-640.webp 640w, /assets/hccf-brand/care-1200.webp 1200w" sizes="(max-width: 560px) 100vw, 50vw" alt="A shared moment with children during HUManity’s work." width="1200" height="1143" fetchpriority="high"><span class="photo-stamp">HUManity IN ACTION</span><figcaption class="photo-note">{icon("heart")}<strong>Every child deserves<br>someone who shows up.</strong><span>From HUManity’s work with children</span></figcaption><span class="photo-spark" aria-hidden="true">✳</span></figure></div></section>
    <div class="wrap campaign-stats" aria-label="Campaign overview"><div><strong>{len(homes):02}</strong><span>Homes selected for support</span></div><div><strong>{len(set(x['district'] for x in homes)):02}</strong><span>Districts across Telangana</span></div><div><strong>₹{sum(x['goal'] for x in homes)//100000} lakh</strong><span>Combined yearly fundraising goal</span></div><div><strong data-overall-received>—</strong><span class="live-label">Confirmed money received</span></div></div>
    {care_banner()}<section class="section" id="homes"><div class="wrap"><div class="section-heading"><div><p class="eyebrow muted">CHOOSE A HOME. BECOME PART OF ITS STORY.</p><h2>{len(homes)} homes.<br>One shared responsibility.</h2></div><p>A leaking roof. A need for beds. A first computer. Meet the homes and choose the difference you want to help make.</p></div><div class="catalogue-tools"><div class="filters" role="group" aria-label="Filter homes by need"><button class="filter" data-filter="all" aria-pressed="true">All homes · {len(homes)}</button><button class="filter" data-filter="essentials" aria-pressed="false">Everyday essentials</button><button class="filter" data-filter="repairs" aria-pressed="false">Repairs & safety</button><button class="filter" data-filter="learning" aria-pressed="false">Digital learning</button></div><label class="search-wrap">{icon('search')}<span class="visually-hidden">Search homes or districts</span><input type="search" id="home-search" placeholder="Search a home or district"></label></div><p class="result-count" id="result-count" aria-live="polite">Showing {len(homes)} selected homes</p><div class="home-grid">{''.join(card(x) for x in homes)}</div><p class="empty-results" id="empty-results" hidden>No homes match this search. Try another district or choose All homes.</p><button class="btn btn-outline more-homes" id="more-homes" hidden>Show more homes ↓</button><p class="totals-explanation">Each home has a ₹6 lakh yearly fundraising goal. Progress includes confirmed one-time gifts and the annual value of active monthly commitments after the first verified payment. The money actually received is shown separately.</p></div></section>
    <section class="section journey" id="how-it-works"><div class="wrap"><div class="journey-top"><div><p class="eyebrow">CARE THAT CONTINUES</p><h2>Small contributions.<br>Steadier tomorrows.</h2><p>HCCF brings supporters around real needs identified through field visits. Together, we can help homes plan beyond the next urgent repair or shortage.</p></div><div class="journey-steps"><div class="journey-step"><span class="step-number">01</span><div><h3>Know the home</h3><p>Read its story, see photographs from the visit and understand the needs identified.</p></div></div><div class="journey-step"><span class="step-number">02</span><div><h3>Choose how to give</h3><p>Make a one-time contribution or commit to monthly support for 12 months.</p></div></div><div class="journey-step"><span class="step-number">03</span><div><h3>Follow the support</h3><p>Your donation is recorded against that home's campaign. Confirmed receipts and future commitments remain distinct.</p></div></div></div></div><div class="future-banner"><div><span class="eyebrow">THE LONGER JOURNEY</span><p>Starting with these {len(homes)} homes. Growing toward 30 childcare institutions.</p></div><strong>30 homes. ₹1.8 crore. A year of care.</strong></div></div></section>
    <section class="section"><div class="wrap faq-layout"><div><p class="eyebrow muted">GIVE WITH CLARITY</p><h2>A few things<br>you may want to know.</h2></div>{faq([('How were these homes selected?','These homes were selected from the HCCF field assessment and the updated support list. Their requirements differ: some need repairs and basic essentials, while Meyers Balabhavan has a specific digital-learning need.'),('Do all the homes need the same kind of support?','Each home has its own priorities. Some need safe roofs, beds or dependable essentials. Others need learning equipment or support for a new facility. Read the individual story to see the needs identified during the field assessment.'),('What does the ₹6 lakh goal cover?','It is the annual campaign target for each home. The home-specific story lists identified needs. Item-wise budgets and allocations will be confirmed before procurement; technical and construction work requires further checks.'),*common_faq[:4]])}</div></section></main>{footer()}'''
def donation_form(home):
    return f'''<aside class="donation-card" id="donate" aria-labelledby="donation-heading"><div class="donation-card-top"><span class="eyebrow">YOUR SUPPORT STARTS HERE</span>{icon('heart')}</div><h2 id="donation-heading">Stand with this home.</h2><p class="home-name">{h(home['name'])}</p>{progress(home)}<p class="previous-donation" id="previous-donation" hidden></p>
    <form id="donation-form"><fieldset id="donation-fields" style="border:0;padding:0;margin:0;min-width:0"><legend class="visually-hidden">Donation details</legend><div id="amount-step"><div class="frequency" role="group" aria-label="Donation frequency"><button type="button" data-frequency="once" aria-pressed="true">Give once</button><button type="button" data-frequency="monthly" aria-pressed="false">Give monthly<span>12 MONTHS OF SUPPORT</span></button></div><label class="field-label" for="donation-amount" id="amount-label">Choose your contribution</label><div class="amount-grid">{''.join(f'<button type="button" data-amount="{v}" aria-pressed="{str(v==1000).lower()}">{rupees(v)}</button>' for v in [500,1000,1500,3000,5000,10000])}</div><div class="custom-amount"><span aria-hidden="true">₹</span><input id="donation-amount" name="amount" type="number" inputmode="numeric" min="1" max="{home['goal']}" step="1" value="1000" required aria-label="Donation amount in rupees"></div><p class="annual-note" id="annual-note" hidden></p><button type="button" class="btn donate-continue" id="continue-donation">Continue with ₹1,000 <span aria-hidden="true">→</span></button></div>
    <div id="donor-step" hidden><div class="details-heading"><h3>Your details</h3><button class="back-amount" type="button" id="edit-amount">Edit amount</button></div><p class="privacy-small" id="selected-gift">One-time gift of ₹1,000</p><label class="donor-field">Full name (as per government ID) *<input name="name" autocomplete="name" minlength="2" maxlength="120" required placeholder="Your full name"></label><label class="donor-field">Email address *<input name="email" type="email" autocomplete="email" maxlength="254" required placeholder="you@example.com"></label><label class="donor-field">Mobile number (+91) *<input name="phone" type="tel" inputmode="tel" autocomplete="tel-national" pattern="[0-9]{{10}}" maxlength="10" required placeholder="10-digit mobile number"></label><div class="donor-row"><label class="donor-field">Government ID type *<select name="idType" required><option value="" disabled selected>Select ID type</option><option value="pan">PAN card</option><option value="aadhaar">Aadhaar card</option><option value="ration">Ration card</option></select></label><label class="donor-field">ID number *<input name="idNumber" autocomplete="off" maxlength="100" required placeholder="As shown on your ID"></label></div><p class="privacy-small">We use these details for your donation receipt and 80G documentation. Eligible donations qualify for a 50% deduction, subject to tax rules and limits. <a href="/privacy" target="_blank" rel="noopener">Privacy policy ↗</a></p><button class="btn donate-continue" id="pay-donation" type="submit">Donate ₹1,000 securely →</button></div></fieldset></form><p class="form-status" id="form-status" role="status" aria-live="polite"></p><button class="btn btn-outline verify-retry" id="verify-retry" type="button" hidden>Check payment confirmation</button><div id="confirmation" hidden></div><button id="donate-again" type="button" class="btn donate-again" hidden>Make another donation →</button><div class="secure-line">{icon('lock')} Secure payments through Razorpay</div><p class="giving-methods">UPI · CARDS · NETBANKING</p><p class="monthly-small">Monthly payments use the recurring methods available in Razorpay.</p><a class="tax-benefit" href="#tax-details">{icon("shield")}<span><strong>50% deduction under 80G</strong><small>For eligible donations · tax rules & limits apply</small></span></a><a class="read-story-mobile text-link" href="#home-story">Read the full story ↓</a></aside>'''
def landing(home):
    thumbs=''.join(f'<button type="button" data-photo="{i}" aria-label="View photo {i+1}: {h(p[1])}" aria-pressed="{str(i==0).lower()}"><img src="{image_path(home,i,640)}" alt="" width="76" height="56" loading="lazy"></button>' for i,p in enumerate(home['photos']))
    needs=''.join(f'<div class="need-item"><span class="need-number">{i+1:02}</span><div><h3>{h(title)}</h3><p>{h(copy)}</p></div></div>' for i,(title,copy) in enumerate(home['needs']))
    return f'''{header(True)}<main id="main"><section class="landing-top">{brand_motif()}<div class="wrap landing-layout"><div class="landing-story"><div class="campaign-owner">{icon("heart")} A HUManity home-support campaign</div><p class="home-eyebrow">{icon('pin')}{h(home['district'])}, Telangana</p><h1 class="landing-title">{h(home['headline'])}</h1><p class="landing-intro">{h(home['intro'])}</p><figure class="landing-photo" id="home-gallery">{photo(home,eager=True,css='gallery-main')}<span class="photo-count" data-photo-count>1 / {len(home['photos'])}</span><figcaption class="photo-caption" data-photo-caption>{h(home['photos'][0][1])}</figcaption></figure><div class="photo-thumbnails" role="group" aria-label="Photographs from the home">{thumbs}</div><div class="home-facts"><span>{icon('people')}{h(home['residents'])}</span><span>{icon('home')}{h(home['since'])}</span><span>{icon('check')}Field-assessed needs</span></div></div>{donation_form(home)}</div></section>
    <div class="wrap detail-body"><div class="detail-content"><section class="story-section" id="home-story"><p class="eyebrow">THE HOME BEHIND YOUR GIFT</p><h2>{h(home['name'])}</h2><div class="prose">{''.join('<p>'+h(p)+'</p>' for p in home['story'])}</div></section><section class="needs-panel"><p class="eyebrow muted">WHERE SUPPORT IS NEEDED</p><h2>Help with what matters<br>in everyday life.</h2>{needs}<p class="allocation-note">{h(home['note'])}</p></section><div class="transparency"><h3>Real needs. A clear yearly goal.</h3><p>This home has a {rupees(home['goal'])} annual fundraising target. Its needs and photographs are drawn from the HCCF social audit. Contributions are recorded for this home's campaign; support will follow confirmed requirements and allocations.</p></div><section class="landing-faq"><h2>Before you give</h2>{faq([('Will my donation be recorded for this home?',f'Yes. Donations made on this page are recorded against {home["name"]} in {home["district"]}. Its progress is separate from other HCCF homes.'),*common_faq])}</section></div><aside class="side-quote"><div class="humanity-promise">{icon("home")}<span class="eyebrow">THE HUManity PROMISE</span><blockquote>“A home is more than a roof. It is the everyday certainty that someone cares.”</blockquote><span class="quote-dash"></span><p>Humanity Uplifting Mankind</p></div><div class="share-block"><h3>Let someone else meet this home.</h3><p>A shared story can bring another person into its circle of support.</p><button class="btn btn-outline" type="button" id="share-home">Share this fundraiser ↗</button><p class="privacy-small" id="share-status" role="status"></p></div></aside></div>
    <section class="closing-appeal"><div class="wrap closing-inner"><div><h2>A little of your kindness.<br>A lasting part of their childhood.</h2><p>Give once, or stay with this home through monthly support.</p></div><a class="btn btn-dark" href="#donate">Support this home <span aria-hidden="true">↗</span></a></div></section></main>{footer(True)}<div class="mobile-donate" id="mobile-donate"><p><strong>Every contribution matters.</strong>{h(home['district'])} · {rupees(home['goal'])} yearly goal</p><a class="btn" href="#donate">Donate now ↗</a></div>'''
def document(content,title,description,url,image,config,css,js):
    cfg=json.dumps(config,ensure_ascii=False).replace('<','\\u003c')
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{h(title)}</title><meta name="description" content="{h(description)}"><link rel="canonical" href="{ORIGIN+url}"><meta property="og:type" content="website"><meta property="og:site_name" content="HUManity Foundation"><meta property="og:title" content="{h(title)}"><meta property="og:description" content="{h(description)}"><meta property="og:url" content="{ORIGIN+url}"><meta property="og:image" content="{ORIGIN+image}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{h(title)}"><meta name="twitter:description" content="{h(description)}"><meta name="twitter:image" content="{ORIGIN+image}"><meta name="theme-color" content="#087da3"><link rel="icon" href="{LOGO}"><link rel="stylesheet" href="/assets/{css}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></head><body class="{config['page']}"><noscript><p class="noscript-note">Enable JavaScript to see live fundraising totals and make a secure donation. For help, call +91 99129 62885.</p></noscript>{content}<script id="hccf-page" type="application/json">{cfg}</script><script type="module" src="/assets/{js}"></script></body></html>'''

(OUT/'assets').mkdir(parents=True,exist_ok=True)
for name in ['campaign.css','campaign.js']:
    raw=(HERE/name).read_bytes(); generated='hccf-'+name.split('.')[0]+'-'+hashlib.sha256(raw).hexdigest()[:10]+'.'+name.split('.')[-1]
    (OUT/'assets'/generated).write_bytes(raw)
    if name.endswith('.css'):css=generated
    else:js=generated
dest=OUT/BASE.lstrip('/');dest.mkdir(parents=True,exist_ok=True)
public_homes=[{k:v for k,v in home.items() if k not in ['story','needs','note','auditPages']} for home in homes]
(dest/'index.html').write_text(document(hub(),f'HUManity ChildCare Institution Fund | Support {len(homes)} Homes','Meet childcare institutions in Telangana. Support their documented needs with one-time or monthly donations and follow each home’s fundraising progress.',BASE,'/assets/hccf-brand/care-social.jpg',{'page':'hub','homes':public_homes},css,js))
for home in homes:
    target=dest/home['id'];target.mkdir(exist_ok=True)
    (target/'index.html').write_text(document(landing(home),f"Support {home['name']} | HUManity",home['summary'],BASE+home['id']+'/',f"/assets/hccf-homes/{home['id']}/social.jpg",{'page':'landing','home':home},css,js))

# PHP allowlist, shared by order creation and public totals; IDs cannot be supplied arbitrarily.
registry={home['id']:{'name':home['name'],'goal':home['goal']*100} for home in homes}
api=OUT/'backend/api/donations';api.mkdir(parents=True,exist_ok=True)
(api/'cci-campaigns.php').write_text("<?php\n// Generated from .hccf/campaign/homes.json. Amounts are in paise.\nreturn json_decode(<<<'HCCF_CAMPAIGNS'\n"+json.dumps(registry,ensure_ascii=False,indent=2)+"\nHCCF_CAMPAIGNS\n, true, 512, JSON_THROW_ON_ERROR);\n")

# The rest of the deployed app remains byte-for-byte unchanged. SPA visits redirect
# to the lightweight static campaign route; direct ad traffic never loads the SPA.
bundle=(SITE/'assets/index-D3rKJrP3.js').read_text()
patched=bundle
for component,route,label in [('nse','/wheelsofhope/fund/','Open the HCCF campaign'),('tie','/donate/','Open the HUManity donation page')]:
    start=patched.index('function '+component+'()')
    # Explicit boundaries for the pinned original bundle. The main donation
    # component is followed by shared checkbox variables; preserve those too.
    boundary='}function ase()' if component=='nse' else '}var ay="Checkbox",'
    end=patched.index(boundary,start)+1
    bridge='function '+component+'(){N.useEffect(()=>{window.location.replace("'+route+'"+window.location.search+window.location.hash)},[]);return N.createElement("main",{style:{padding:"80px 24px",textAlign:"center"}},N.createElement("a",{href:"'+route+'"},"'+label+'"))}\n'
    patched=patched[:start]+bridge+patched[end:]
bundle_name='index-hccf-'+hashlib.sha256(patched.encode()).hexdigest()[:10]+'.js'
(OUT/'assets'/bundle_name).write_text(patched)
index=(SITE/'index.html').read_text()
index=re.sub(r'/assets/index-(?:hccf-[a-f0-9]+|D3rKJrP3)\.js','/assets/'+bundle_name,index)
index=re.sub(r'<link rel="stylesheet" href="/assets/cci-fundraiser\.css[^\"]*">\s*','',index)
(OUT/'index.html').write_text(index)
(HERE/'build-manifest.json').write_text(json.dumps({'bundle':bundle_name,'css':css,'js':js,'routes':[BASE]+[BASE+x['id']+'/' for x in homes]},indent=2))
print(f'Built HCCF hub + {len(homes)} standalone home pages; shared assets: {css}, {js}.')
